export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white max-w-2xl mx-auto px-6 py-16">
      <a href="/" className="text-sm text-zinc-400 hover:text-zinc-700 mb-8 inline-block">← Back</a>
      <h1 className="text-3xl font-bold text-zinc-900 mb-2">Terms of Service</h1>
      <p className="text-sm text-zinc-400 mb-8">Last updated: March 2025</p>
      <div className="space-y-6 text-zinc-600 leading-relaxed text-sm">
        <section>
          <h2 className="font-semibold text-zinc-900 mb-2">Use of service</h2>
          <p>AskWomensAI is provided for informational purposes only. You agree not to use it for unlawful purposes, to generate harmful content, or to attempt to circumvent rate limits or abuse the service.</p>
        </section>
        <section>
          <h2 className="font-semibold text-zinc-900 mb-2">Medical disclaimer</h2>
          <p>AskWomensAI does not provide medical advice, diagnosis, or treatment recommendations. All AI-generated responses are for general informational purposes only. Always consult a qualified healthcare provider before making any health-related decisions.</p>
        </section>
        <section>
          <h2 className="font-semibold text-zinc-900 mb-2">No warranties</h2>
          <p>The service is provided "as is" without warranties of any kind. AI responses may be inaccurate, incomplete, or out of date. AskWomensAI is not liable for any decisions made based on responses generated by the service.</p>
        </section>
        <section>
          <h2 className="font-semibold text-zinc-900 mb-2">Changes</h2>
          <p>We may update these terms at any time. Continued use of the service constitutes acceptance of the updated terms.</p>
        </section>
        <section>
          <h2 className="font-semibold text-zinc-900 mb-2">Contact</h2>
          <p>For questions, contact us at hello@AskWomensAI.com.</p>
        </section>
      </div>
    </div>
  );
}
