import { InteriorHeader } from '@/components/interior-header';

export default function TermsPage() {
  return (
    <div className="min-h-screen" style={{ background: 'linear-gradient(160deg, #FDF5F8 0%, #FBF8F5 45%, #F6EFF9 100%)' }}>
      <InteriorHeader />
      <div className="max-w-2xl mx-auto px-6 py-12">
        <h1 style={{ fontFamily: 'var(--font-playfair)', fontSize: '36px', fontWeight: 700, color: '#1C1714', marginBottom: '8px' }}>Terms of Service</h1>
        <p className="text-sm mb-10" style={{ color: '#AFA8A2' }}>Last updated: March 2026</p>
        <div className="space-y-8" style={{ color: '#7A6E67', lineHeight: 1.8, fontSize: '15px' }}>
          <section>
            <h2 style={{ fontFamily: 'var(--font-playfair)', fontWeight: 600, color: '#1C1714', fontSize: '18px', marginBottom: '8px' }}>Use of service</h2>
            <p>AskWomensAI is provided for informational purposes only. You agree not to use it for unlawful purposes, to generate harmful content, or to attempt to circumvent rate limits or abuse the service.</p>
          </section>
          <section>
            <h2 style={{ fontFamily: 'var(--font-playfair)', fontWeight: 600, color: '#1C1714', fontSize: '18px', marginBottom: '8px' }}>Medical disclaimer</h2>
            <p>AskWomensAI does not provide medical advice, diagnosis, or treatment recommendations. All AI-generated responses are for general informational purposes only. Always consult a qualified healthcare provider before making any health-related decisions.</p>
          </section>
          <section>
            <h2 style={{ fontFamily: 'var(--font-playfair)', fontWeight: 600, color: '#1C1714', fontSize: '18px', marginBottom: '8px' }}>No warranties</h2>
            <p>The service is provided &quot;as is&quot; without warranties of any kind. AI responses may be inaccurate, incomplete, or out of date. AskWomensAI is not liable for any decisions made based on responses generated by the service.</p>
          </section>
          <section>
            <h2 style={{ fontFamily: 'var(--font-playfair)', fontWeight: 600, color: '#1C1714', fontSize: '18px', marginBottom: '8px' }}>Changes</h2>
            <p>We may update these terms at any time. Continued use of the service constitutes acceptance of the updated terms.</p>
          </section>
          <section>
            <h2 style={{ fontFamily: 'var(--font-playfair)', fontWeight: 600, color: '#1C1714', fontSize: '18px', marginBottom: '8px' }}>Contact</h2>
            <p>For questions, contact us at <a href="mailto:hello@askwomensai.com" style={{ color: '#9B4163' }}>hello@askwomensai.com</a>.</p>
          </section>
        </div>
      </div>
    </div>
  );
}
