import re
from collections import Counter

def slugify(text):
    text = text.lower()
    text = re.sub(r"[^\w\s-]", "", text)
    text = re.sub(r"[\s_]+", "-", text)
    text = re.sub(r"-+", "-", text)
    return text.strip("-")[:80]

# (question, category, age_group, is_weird, is_featured)
questions = [
    # ── HEALTH & BODY (80) ───────────────────────────────────────────
    ("Why do I get so tired before my period?", "Health & Body", "all", False, True),
    ("Is it normal to feel bloated every day?", "Health & Body", "all", False, False),
    ("What causes painful periods and what actually helps?", "Health & Body", "all", False, True),
    ("Why does my hair fall out more in the shower some months?", "Health & Body", "all", False, False),
    ("What are the early signs of iron deficiency in women?", "Health & Body", "all", False, True),
    ("Why do I get headaches right before my period?", "Health & Body", "all", False, False),
    ("Is it normal to feel extremely hungry right before my period?", "Health & Body", "all", False, False),
    ("What causes a heavy period and when should I be concerned?", "Health & Body", "all", False, True),
    ("Why do I get acne on my chin every month?", "Health & Body", "all", False, False),
    ("What does it mean if my period blood is brown?", "Health & Body", "all", False, False),
    ("Can stress really delay your period?", "Health & Body", "all", False, True),
    ("What are signs that your thyroid might be off?", "Health & Body", "all", False, True),
    ("Why do I feel cold all the time even when others dont?", "Health & Body", "all", False, False),
    ("What causes brain fog and how do you fix it?", "Health & Body", "all", False, True),
    ("Is it normal to have an irregular period in your 30s?", "Health & Body", "30s", False, False),
    ("What are the symptoms of PCOS and how is it diagnosed?", "Health & Body", "all", False, True),
    ("Why do I wake up at 3am every night?", "Health & Body", "all", False, True),
    ("Can birth control affect your mood long term?", "Health & Body", "all", False, True),
    ("What is endometriosis and what does it feel like?", "Health & Body", "all", False, True),
    ("Why do my joints ache more around my period?", "Health & Body", "all", False, False),
    ("What causes chronic UTIs in women and how to prevent them?", "Health & Body", "all", False, True),
    ("Is spotting between periods ever normal?", "Health & Body", "all", False, False),
    ("Why do I get dizzy when I stand up too fast?", "Health & Body", "all", False, False),
    ("What is the difference between a yeast infection and BV?", "Health & Body", "all", False, True),
    ("Why does my stomach hurt so much during my period?", "Health & Body", "all", False, False),
    ("What are signs of anemia in women?", "Health & Body", "all", False, True),
    ("Can you have a period and still be pregnant?", "Health & Body", "all", False, False),
    ("What causes breast tenderness throughout the month?", "Health & Body", "all", False, False),
    ("Is it normal for periods to get worse after having a baby?", "Health & Body", "30s", False, False),
    ("Why am I gaining weight even though my diet hasnt changed?", "Health & Body", "all", False, True),
    ("What does low estrogen feel like?", "Health & Body", "all", False, True),
    ("Can anxiety cause physical symptoms in your body?", "Health & Body", "all", False, True),
    ("What are signs your cortisol is too high?", "Health & Body", "all", False, True),
    ("Why do I bruise so easily?", "Health & Body", "all", False, False),
    ("What causes night sweats in women under 40?", "Health & Body", "20s,30s,40s", False, False),
    ("Is it normal to feel nauseous during ovulation?", "Health & Body", "all", False, False),
    ("What are the symptoms of fibroids?", "Health & Body", "30s,40s", False, True),
    ("Why do I get so emotional the week before my period?", "Health & Body", "all", False, False),
    ("Can diet really affect your period?", "Health & Body", "all", False, True),
    ("What are signs of vitamin D deficiency in women?", "Health & Body", "all", False, True),
    ("Why do I have pain during sex sometimes?", "Health & Body", "all", False, True),
    ("What causes bloating after eating even healthy food?", "Health & Body", "all", False, False),
    ("Is it normal to skip a period once in a while?", "Health & Body", "all", False, False),
    ("What are signs of insulin resistance in women?", "Health & Body", "all", False, True),
    ("Can lack of sleep affect your hormones?", "Health & Body", "all", False, True),
    ("Why do I get heart palpitations sometimes?", "Health & Body", "all", False, False),
    ("What causes low libido in women and what helps?", "Health & Body", "all", False, True),
    ("Is it normal to have very light periods?", "Health & Body", "all", False, False),
    ("What are the early signs of autoimmune disease in women?", "Health & Body", "all", False, True),
    ("Why do I feel anxious right before my period?", "Health & Body", "all", False, False),
    ("What does a normal vaginal discharge look like?", "Health & Body", "all", False, True),
    ("Can coffee affect your hormones or period?", "Health & Body", "all", False, False),
    ("Why do I get leg cramps at night?", "Health & Body", "all", False, False),
    ("What are the signs of perimenopause starting?", "Health & Body", "40s", False, True),
    ("Is chronic fatigue syndrome more common in women?", "Health & Body", "all", False, False),
    ("What causes hormonal headaches and how to treat them?", "Health & Body", "all", False, True),
    ("Why do I get constipated right before my period?", "Health & Body", "all", False, False),
    ("What are signs that your gut health needs attention?", "Health & Body", "all", False, True),
    ("Can you have hypothyroidism with normal TSH?", "Health & Body", "all", False, False),
    ("What does PMDD feel like versus normal PMS?", "Health & Body", "all", False, True),
    ("Why do I feel worse after eating certain foods?", "Health & Body", "all", False, False),
    ("Is it normal to have a tilted uterus?", "Health & Body", "all", False, False),
    ("What causes ovarian cysts and are they dangerous?", "Health & Body", "all", False, True),
    ("Why does my lower back hurt so much during my period?", "Health & Body", "all", False, False),
    ("What are the symptoms of Hashimotos thyroiditis?", "Health & Body", "all", False, True),
    ("Can you get a UTI from sex?", "Health & Body", "all", False, False),
    ("What causes a missed period other than pregnancy?", "Health & Body", "all", False, True),
    ("Why do I get hot flashes in my 30s?", "Health & Body", "30s", False, False),
    ("What are the symptoms of adrenal fatigue?", "Health & Body", "all", False, False),
    ("Is it normal to feel very fatigued after ovulation?", "Health & Body", "all", False, False),
    ("What causes adult acne in women in their 30s and 40s?", "Health & Body", "30s,40s", False, True),
    ("Can birth control cause nutrient deficiencies?", "Health & Body", "all", False, True),
    ("Why do I get flu-like symptoms before my period?", "Health & Body", "all", False, False),
    ("What are signs your liver needs support?", "Health & Body", "all", False, False),
    ("Is irregular ovulation a sign of something wrong?", "Health & Body", "all", False, False),
    ("What causes interstitial cystitis and how is it treated?", "Health & Body", "all", False, False),
    ("Why do I feel so thirsty all the time?", "Health & Body", "all", False, False),
    ("What blood tests should women get every year?", "Health & Body", "all", False, True),
    ("Can poor sleep cause weight gain in women?", "Health & Body", "all", False, True),
    # ── HORMONES & MENOPAUSE (50) ────────────────────────────────────
    ("What are the first signs of perimenopause?", "Hormones & Menopause", "40s,50s+", False, True),
    ("How long does perimenopause typically last?", "Hormones & Menopause", "40s,50s+", False, True),
    ("What is the difference between perimenopause and menopause?", "Hormones & Menopause", "40s,50s+", False, True),
    ("Does menopause cause weight gain and can you prevent it?", "Hormones & Menopause", "40s,50s+", False, True),
    ("What helps with hot flashes naturally?", "Hormones & Menopause", "40s,50s+", False, True),
    ("Is HRT safe and what are the real risks?", "Hormones & Menopause", "40s,50s+", False, True),
    ("What causes mood swings during perimenopause?", "Hormones & Menopause", "40s,50s+", False, False),
    ("Why do women lose sleep during menopause?", "Hormones & Menopause", "40s,50s+", False, True),
    ("What does low progesterone feel like?", "Hormones & Menopause", "all", False, True),
    ("What is estrogen dominance and what are the symptoms?", "Hormones & Menopause", "all", False, True),
    ("Can you still get pregnant during perimenopause?", "Hormones & Menopause", "40s,50s+", False, True),
    ("What causes vaginal dryness and what actually helps?", "Hormones & Menopause", "40s,50s+", False, True),
    ("How do you know if your estrogen is too low?", "Hormones & Menopause", "all", False, True),
    ("What are bioidentical hormones and are they better?", "Hormones & Menopause", "40s,50s+", False, False),
    ("Does menopause affect memory and cognitive function?", "Hormones & Menopause", "40s,50s+", False, True),
    ("What vitamins and supplements help with perimenopause symptoms?", "Hormones & Menopause", "40s,50s+", False, True),
    ("Can exercise reduce menopause symptoms?", "Hormones & Menopause", "40s,50s+", False, True),
    ("What foods help with hormonal balance?", "Hormones & Menopause", "all", False, True),
    ("What causes irregular periods leading up to menopause?", "Hormones & Menopause", "40s,50s+", False, False),
    ("Does menopause affect bone density?", "Hormones & Menopause", "40s,50s+", False, True),
    ("What is premature menopause and what causes it?", "Hormones & Menopause", "all", False, True),
    ("Can stress trigger early menopause?", "Hormones & Menopause", "40s,50s+", False, False),
    ("What are the symptoms of too much estrogen?", "Hormones & Menopause", "all", False, True),
    ("Why does menopause cause anxiety and how to manage it?", "Hormones & Menopause", "40s,50s+", False, True),
    ("What is the average age for menopause?", "Hormones & Menopause", "all", False, False),
    ("How does testosterone affect womens health?", "Hormones & Menopause", "all", False, True),
    ("Does menopause make you more prone to heart disease?", "Hormones & Menopause", "40s,50s+", False, True),
    ("What is genitourinary syndrome of menopause?", "Hormones & Menopause", "40s,50s+", False, False),
    ("Can diet help reduce hot flashes?", "Hormones & Menopause", "40s,50s+", False, True),
    ("What causes joint pain in menopause?", "Hormones & Menopause", "40s,50s+", False, True),
    ("Is low libido during menopause normal and what helps?", "Hormones & Menopause", "40s,50s+", False, True),
    ("What does a hormone panel test tell you?", "Hormones & Menopause", "all", False, True),
    ("Can perimenopause cause depression?", "Hormones & Menopause", "40s,50s+", False, True),
    ("What are phytoestrogens and do they help with menopause?", "Hormones & Menopause", "40s,50s+", False, False),
    ("Why do women gain belly fat during menopause?", "Hormones & Menopause", "40s,50s+", False, True),
    ("Does menopause affect skin and hair?", "Hormones & Menopause", "40s,50s+", False, True),
    ("What is the luteal phase and why does it affect mood?", "Hormones & Menopause", "all", False, True),
    ("Can you balance hormones without medication?", "Hormones & Menopause", "all", False, True),
    ("What are symptoms of cortisol imbalance in women?", "Hormones & Menopause", "all", False, True),
    ("How do you track your cycle to understand your hormones?", "Hormones & Menopause", "all", False, True),
    ("What does progesterone do and why do women need it?", "Hormones & Menopause", "all", False, True),
    ("Is it safe to take melatonin for menopause sleep problems?", "Hormones & Menopause", "40s,50s+", False, False),
    ("What causes hormonal acne in women over 40?", "Hormones & Menopause", "40s", False, True),
    ("Does menopause affect your relationship or sex drive?", "Hormones & Menopause", "40s,50s+", False, True),
    ("What is a Dutch hormone test?", "Hormones & Menopause", "all", False, False),
    ("Why does estrogen loss cause weight gain in your midsection?", "Hormones & Menopause", "40s,50s+", False, True),
    ("Can you still have a sex life after menopause?", "Hormones & Menopause", "50s+", False, True),
    ("What lifestyle changes make the biggest difference during menopause?", "Hormones & Menopause", "40s,50s+", False, True),
    ("Why does menopause cause urinary incontinence?", "Hormones & Menopause", "40s,50s+", False, True),
    ("What is the best diet for hormonal health in women?", "Hormones & Menopause", "all", False, True),
    # ── FITNESS & EXERCISE (50) ──────────────────────────────────────
    ("Can women take creatine and does it actually work?", "Fitness & Exercise", "all", False, True),
    ("What is the best type of exercise for fat loss in women?", "Fitness & Exercise", "all", False, True),
    ("Should women lift heavy weights?", "Fitness & Exercise", "all", False, True),
    ("How many times a week should women strength train?", "Fitness & Exercise", "all", False, True),
    ("What is the best workout for women over 40?", "Fitness & Exercise", "40s,50s+", False, True),
    ("Why is it harder to lose weight after 35?", "Fitness & Exercise", "30s,40s", False, True),
    ("Should women do cardio or weights for weight loss?", "Fitness & Exercise", "all", False, True),
    ("What is the best way for women to build muscle?", "Fitness & Exercise", "all", False, True),
    ("Does running ruin your knees over time?", "Fitness & Exercise", "all", False, False),
    ("What is zone 2 cardio and why do women need it?", "Fitness & Exercise", "all", False, True),
    ("How do you avoid losing muscle while losing fat?", "Fitness & Exercise", "all", False, True),
    ("What is the best workout split for women?", "Fitness & Exercise", "all", False, True),
    ("Can you exercise during your period?", "Fitness & Exercise", "all", False, True),
    ("What exercises are best for pelvic floor strength?", "Fitness & Exercise", "all", False, True),
    ("How do you get started with strength training as a beginner?", "Fitness & Exercise", "all", False, True),
    ("Is walking enough exercise for women?", "Fitness & Exercise", "all", False, True),
    ("What is the best exercise to do during menopause?", "Fitness & Exercise", "40s,50s+", False, True),
    ("How much protein do women need when working out?", "Fitness & Exercise", "all", False, True),
    ("Does working out affect your period?", "Fitness & Exercise", "all", False, False),
    ("How long does it take to see results from working out?", "Fitness & Exercise", "all", False, True),
    ("What causes muscle soreness and how do you recover faster?", "Fitness & Exercise", "all", False, False),
    ("What is the best pre-workout for women?", "Fitness & Exercise", "all", False, False),
    ("Can you exercise too much and hurt your hormones?", "Fitness & Exercise", "all", False, True),
    ("What are the best exercises for a flat stomach?", "Fitness & Exercise", "all", False, False),
    ("How do women over 50 build strength effectively?", "Fitness & Exercise", "50s+", False, True),
    ("Is Pilates actually effective for strength or just flexibility?", "Fitness & Exercise", "all", False, True),
    ("What is the best workout for stress and anxiety?", "Fitness & Exercise", "all", False, True),
    ("How do you work out when youre always tired?", "Fitness & Exercise", "all", False, True),
    ("What are the best exercises for bone density in women?", "Fitness & Exercise", "40s,50s+", False, True),
    ("How do you track fitness progress without focusing on the scale?", "Fitness & Exercise", "all", False, True),
    ("Does yoga count as exercise?", "Fitness & Exercise", "all", False, False),
    ("What causes runners knee and how do you fix it?", "Fitness & Exercise", "all", False, False),
    ("How do you stay consistent with workouts when life is busy?", "Fitness & Exercise", "all", False, True),
    ("What is HIIT and is it good for women?", "Fitness & Exercise", "all", False, True),
    ("What are the best exercises after having a baby?", "Fitness & Exercise", "30s", False, True),
    ("Is 30 minutes of exercise a day enough?", "Fitness & Exercise", "all", False, True),
    ("What are the best exercises for lower back pain?", "Fitness & Exercise", "all", False, True),
    ("How do you use cycle syncing to improve your workouts?", "Fitness & Exercise", "all", False, True),
    ("What are the signs youre overtraining?", "Fitness & Exercise", "all", False, False),
    ("What is the best workout if you have PCOS?", "Fitness & Exercise", "all", False, True),
    ("Does cold plunging actually work for recovery?", "Fitness & Exercise", "all", False, False),
    ("How do you lose weight without losing your breasts?", "Fitness & Exercise", "all", False, False),
    ("What are the best exercises for hip dips?", "Fitness & Exercise", "all", False, False),
    ("Is working out fasted better for women?", "Fitness & Exercise", "all", False, True),
    ("What is the best workout for body recomposition?", "Fitness & Exercise", "all", False, True),
    ("How do you prevent injuries when strength training?", "Fitness & Exercise", "all", False, False),
    ("What makes womens fitness different from mens fitness?", "Fitness & Exercise", "all", False, True),
    ("How do you train around your menstrual cycle?", "Fitness & Exercise", "all", False, True),
    ("What are the best exercises for reducing anxiety?", "Fitness & Exercise", "all", False, True),
    ("Do women need rest days from working out?", "Fitness & Exercise", "all", False, False),
    # ── NUTRITION & DIET (50) ────────────────────────────────────────
    ("How much protein should women eat per day?", "Nutrition & Diet", "all", False, True),
    ("What is the best diet for women over 40?", "Nutrition & Diet", "40s,50s+", False, True),
    ("Does intermittent fasting work for women?", "Nutrition & Diet", "all", False, True),
    ("What foods help balance hormones naturally?", "Nutrition & Diet", "all", False, True),
    ("Is a high-protein diet safe for women?", "Nutrition & Diet", "all", False, True),
    ("What are the best foods for energy and reducing fatigue?", "Nutrition & Diet", "all", False, True),
    ("What vitamins should women take daily?", "Nutrition & Diet", "all", False, True),
    ("Is the keto diet good for women?", "Nutrition & Diet", "all", False, True),
    ("What foods cause hormonal acne?", "Nutrition & Diet", "all", False, True),
    ("What is the Mediterranean diet and is it good for women?", "Nutrition & Diet", "all", False, True),
    ("How do you stop sugar cravings during your period?", "Nutrition & Diet", "all", False, True),
    ("What are the best anti-inflammatory foods for women?", "Nutrition & Diet", "all", False, True),
    ("What foods help with PMS symptoms?", "Nutrition & Diet", "all", False, True),
    ("How much water should women drink each day?", "Nutrition & Diet", "all", False, False),
    ("What causes constant food cravings and how to manage them?", "Nutrition & Diet", "all", False, True),
    ("Is dairy bad for hormones or PCOS?", "Nutrition & Diet", "all", False, True),
    ("What does seed cycling do and does it actually work?", "Nutrition & Diet", "all", False, True),
    ("What are the best foods for gut health in women?", "Nutrition & Diet", "all", False, True),
    ("How do you eat to support your thyroid?", "Nutrition & Diet", "all", False, True),
    ("What are the best sources of collagen in food?", "Nutrition & Diet", "all", False, False),
    ("Is soy bad for womens hormones?", "Nutrition & Diet", "all", False, True),
    ("What is intuitive eating and does it work?", "Nutrition & Diet", "all", False, True),
    ("How much calcium do women need and what foods have it?", "Nutrition & Diet", "all", False, False),
    ("What are the best foods for menopausal women?", "Nutrition & Diet", "40s,50s+", False, True),
    ("Does alcohol affect womens hormones?", "Nutrition & Diet", "all", False, True),
    ("What are signs youre not eating enough protein?", "Nutrition & Diet", "all", False, True),
    ("Is gluten-free diet actually healthier for women?", "Nutrition & Diet", "all", False, False),
    ("What are the best foods for fertility?", "Nutrition & Diet", "20s,30s", False, True),
    ("Does coffee affect hormones or fertility in women?", "Nutrition & Diet", "all", False, True),
    ("What is the best meal timing for women who work out?", "Nutrition & Diet", "all", False, True),
    ("How do you calculate how many calories you need?", "Nutrition & Diet", "all", False, False),
    ("What are the best plant-based protein sources for women?", "Nutrition & Diet", "all", False, True),
    ("How does gut health affect mental health in women?", "Nutrition & Diet", "all", False, True),
    ("Is magnesium good for women and what does it do?", "Nutrition & Diet", "all", False, True),
    ("What foods should you avoid when trying to balance cortisol?", "Nutrition & Diet", "all", False, True),
    ("What is a low-glycemic diet and who needs it?", "Nutrition & Diet", "all", False, False),
    ("What causes iron deficiency in women and what foods fix it?", "Nutrition & Diet", "all", False, True),
    ("Can cutting calories actually slow your metabolism?", "Nutrition & Diet", "all", False, True),
    ("What are the best foods for clear skin?", "Nutrition & Diet", "all", False, True),
    ("How do you stop binge eating at night?", "Nutrition & Diet", "all", False, True),
    ("What is creatine and should women take it?", "Nutrition & Diet", "all", False, True),
    ("Are protein shakes necessary or just for bodybuilders?", "Nutrition & Diet", "all", False, False),
    ("What is the best diet for PCOS?", "Nutrition & Diet", "all", False, True),
    ("Does fasting affect womens hormones differently than mens?", "Nutrition & Diet", "all", False, True),
    ("What does omega-3 do for womens health?", "Nutrition & Diet", "all", False, True),
    ("How do you eat healthy when youre always exhausted?", "Nutrition & Diet", "all", False, True),
    ("What are the best foods for bone health in women?", "Nutrition & Diet", "40s,50s+", False, True),
    ("Is eating fat actually bad for hormones?", "Nutrition & Diet", "all", False, True),
    ("What are the best superfoods for womens health?", "Nutrition & Diet", "all", False, False),
    ("How do you meal prep when you have no time?", "Nutrition & Diet", "all", False, False),
    # ── SEX & INTIMACY (40) ──────────────────────────────────────────
    ("What causes low libido in women and what actually helps?", "Sex & Intimacy", "all", False, True),
    ("Is it normal to have a different libido than your partner?", "Sex & Intimacy", "all", False, True),
    ("Why does sex hurt sometimes and what can I do?", "Sex & Intimacy", "all", False, True),
    ("What is the best lubricant for sex and does it matter?", "Sex & Intimacy", "all", False, True),
    ("Can birth control lower your sex drive?", "Sex & Intimacy", "all", False, True),
    ("What causes vaginal dryness in younger women?", "Sex & Intimacy", "20s,30s", False, True),
    ("Is it normal for sex drive to change throughout the month?", "Sex & Intimacy", "all", False, True),
    ("What are the best ways to increase libido naturally?", "Sex & Intimacy", "all", False, True),
    ("How does stress affect your sex drive?", "Sex & Intimacy", "all", False, True),
    ("What is the difference between libido and arousal?", "Sex & Intimacy", "all", False, False),
    ("Why cant I orgasm and what can help?", "Sex & Intimacy", "all", False, True),
    ("Is it normal to lose interest in sex after having kids?", "Sex & Intimacy", "30s,40s", False, True),
    ("What are signs of intimacy issues in a relationship?", "Sex & Intimacy", "all", False, True),
    ("How do you rebuild intimacy after a rough patch?", "Sex & Intimacy", "all", False, True),
    ("Does testosterone affect womens libido?", "Sex & Intimacy", "all", False, True),
    ("What causes pain during or after sex?", "Sex & Intimacy", "all", False, True),
    ("How does menopause affect your sex life?", "Sex & Intimacy", "40s,50s+", False, True),
    ("Is it normal to have a higher sex drive before your period?", "Sex & Intimacy", "all", False, False),
    ("What is vaginismus and how is it treated?", "Sex & Intimacy", "all", False, True),
    ("Can antidepressants cause low libido and what can you do?", "Sex & Intimacy", "all", False, True),
    ("How do you talk to your partner about a mismatched sex drive?", "Sex & Intimacy", "all", False, True),
    ("What are the health benefits of regular sex for women?", "Sex & Intimacy", "all", False, False),
    ("What causes loss of sensation during sex?", "Sex & Intimacy", "all", False, True),
    ("Is it normal to not want sex during certain parts of your cycle?", "Sex & Intimacy", "all", False, False),
    ("What is responsive vs spontaneous desire in women?", "Sex & Intimacy", "all", False, True),
    ("How long is it normal to go without sex in a relationship?", "Sex & Intimacy", "all", False, True),
    ("What are the most common sexual health issues for women?", "Sex & Intimacy", "all", False, True),
    ("What is pelvic floor dysfunction and how does it affect sex?", "Sex & Intimacy", "all", False, True),
    ("Does getting older change your sex drive?", "Sex & Intimacy", "40s,50s+", False, True),
    ("What are realistic expectations for sex in a long-term relationship?", "Sex & Intimacy", "all", False, True),
    ("How does body image affect intimacy?", "Sex & Intimacy", "all", False, True),
    ("What is a normal frequency for sex in a healthy relationship?", "Sex & Intimacy", "all", False, True),
    ("Can vaginal atrophy be reversed?", "Sex & Intimacy", "40s,50s+", False, True),
    ("What should I know about STI testing as a sexually active woman?", "Sex & Intimacy", "20s,30s", False, True),
    ("Does birth control affect how you choose a partner?", "Sex & Intimacy", "all", False, False),
    ("What causes a sudden drop in sex drive?", "Sex & Intimacy", "all", False, True),
    ("Is it normal to feel less interested in sex after having a baby?", "Sex & Intimacy", "30s", False, True),
    ("How does anxiety affect libido in women?", "Sex & Intimacy", "all", False, True),
    ("What are the best exercises for better sex?", "Sex & Intimacy", "all", False, False),
    ("Why does my sex drive go up during ovulation?", "Sex & Intimacy", "all", False, False),
    # ── RELATIONSHIPS (50) ───────────────────────────────────────────
    ("How do you know when a relationship is worth fighting for?", "Relationships", "all", False, True),
    ("What are the signs of an emotionally unavailable partner?", "Relationships", "all", False, True),
    ("What does a healthy relationship actually look like?", "Relationships", "all", False, True),
    ("How do you stop attracting the same type of person?", "Relationships", "all", False, True),
    ("What are red flags in a new relationship?", "Relationships", "all", False, True),
    ("How do you know if someone is right for you long-term?", "Relationships", "all", False, True),
    ("What causes someone to lose feelings in a relationship?", "Relationships", "all", False, True),
    ("How do you communicate better in a relationship?", "Relationships", "all", False, True),
    ("What is attachment theory and how does it affect relationships?", "Relationships", "all", False, True),
    ("Is it normal for the honeymoon phase to end?", "Relationships", "all", False, True),
    ("How do you recover from a bad breakup?", "Relationships", "all", False, True),
    ("What are signs of a narcissistic partner?", "Relationships", "all", False, True),
    ("How do you maintain friendships when youre in a serious relationship?", "Relationships", "all", False, True),
    ("What causes trust issues in relationships and how to heal them?", "Relationships", "all", False, True),
    ("How do you set boundaries with a controlling partner?", "Relationships", "all", False, True),
    ("What is the difference between love and attachment?", "Relationships", "all", False, True),
    ("What are the signs of a one-sided relationship?", "Relationships", "all", False, True),
    ("How do you leave a relationship when you still love someone?", "Relationships", "all", False, True),
    ("What makes couples stay together long-term?", "Relationships", "all", False, True),
    ("How do you rebuild trust after its been broken?", "Relationships", "all", False, True),
    ("What is stonewalling and how do you deal with it?", "Relationships", "all", False, True),
    ("What does a trauma bond feel like?", "Relationships", "all", False, True),
    ("How do you handle a partner who shuts down during arguments?", "Relationships", "all", False, True),
    ("What causes codependency and how to break it?", "Relationships", "all", False, True),
    ("How do you know if youre in the right relationship or just comfortable?", "Relationships", "all", False, True),
    ("What are the stages of grief after a relationship ends?", "Relationships", "all", False, True),
    ("How long does it take to get over a serious breakup?", "Relationships", "all", False, False),
    ("What is love bombing and how do you recognize it?", "Relationships", "all", False, True),
    ("How do you stop being jealous in a relationship?", "Relationships", "all", False, True),
    ("Is couples therapy worth it?", "Relationships", "all", False, True),
    ("How do you date again after a long relationship ends?", "Relationships", "all", False, True),
    ("What are signs of emotional abuse in a relationship?", "Relationships", "all", False, True),
    ("How do you maintain your identity when youre in a relationship?", "Relationships", "all", False, True),
    ("What causes a loss of attraction to a partner over time?", "Relationships", "all", False, True),
    ("How do you deal with a partner who is bad at communicating?", "Relationships", "all", False, True),
    ("What is the difference between healthy and unhealthy jealousy?", "Relationships", "all", False, False),
    ("How do you protect your mental health while dating?", "Relationships", "all", False, True),
    ("What are signs youre staying in a relationship out of fear?", "Relationships", "all", False, True),
    ("How do you handle disagreements about money with a partner?", "Relationships", "all", False, True),
    ("What makes someone a good long-term partner?", "Relationships", "all", False, True),
    ("How do you stop being the person who always gives more?", "Relationships", "all", False, True),
    ("What does emotional intimacy mean and how do you build it?", "Relationships", "all", False, True),
    ("What causes relationships to feel stale and how to fix it?", "Relationships", "all", False, True),
    ("How do you know if your partner respects you?", "Relationships", "all", False, True),
    ("What are signs of a secure attachment style?", "Relationships", "all", False, True),
    ("Is it normal to fight a lot in the early stages of a relationship?", "Relationships", "all", False, False),
    ("How do you handle a partner who refuses to go to therapy?", "Relationships", "all", False, True),
    ("What are the biggest relationship mistakes women make in their 20s?", "Relationships", "20s", False, True),
    ("How do you keep a long-distance relationship strong?", "Relationships", "all", False, False),
    ("What is the best way to end a relationship kindly but clearly?", "Relationships", "all", False, True),
    # ── CAREER & MONEY (40) ──────────────────────────────────────────
    ("How do women negotiate salary effectively?", "Career & Money", "all", False, True),
    ("What are signs youre underpaid and what should you do?", "Career & Money", "all", False, True),
    ("How do you ask for a raise without feeling awkward?", "Career & Money", "all", False, True),
    ("What is the best way for women to start investing?", "Career & Money", "all", False, True),
    ("How do you build an emergency fund from scratch?", "Career & Money", "all", False, True),
    ("What are the biggest financial mistakes women make in their 30s?", "Career & Money", "30s", False, True),
    ("How do you handle a toxic work environment?", "Career & Money", "all", False, True),
    ("What are signs you need to leave your job?", "Career & Money", "all", False, True),
    ("How do you change careers in your 30s or 40s?", "Career & Money", "30s,40s", False, True),
    ("What is the best retirement savings strategy for women?", "Career & Money", "all", False, True),
    ("How do women build wealth differently than men?", "Career & Money", "all", False, True),
    ("What should women know about financial independence?", "Career & Money", "all", False, True),
    ("How do you manage finances when one partner earns more?", "Career & Money", "all", False, True),
    ("What are signs of imposter syndrome and how do you overcome it?", "Career & Money", "all", False, True),
    ("How do you build confidence at work?", "Career & Money", "all", False, True),
    ("What is the gender pay gap and how does it affect your career?", "Career & Money", "all", False, True),
    ("How do you set boundaries with a demanding boss?", "Career & Money", "all", False, True),
    ("What are the best side hustles for women?", "Career & Money", "all", False, True),
    ("How do you save money when youre living paycheck to paycheck?", "Career & Money", "all", False, True),
    ("What should women know about divorce and finances?", "Career & Money", "all", False, True),
    ("How do you negotiate a job offer as a woman?", "Career & Money", "all", False, True),
    ("What is a reasonable savings rate for women in their 30s?", "Career & Money", "30s", False, True),
    ("How do you get promoted when you keep being overlooked?", "Career & Money", "all", False, True),
    ("What is the best way to pay off debt fast?", "Career & Money", "all", False, True),
    ("How do you build a personal brand at work?", "Career & Money", "all", False, True),
    ("What are the best investments for beginners?", "Career & Money", "all", False, True),
    ("How do you deal with a male-dominated work environment?", "Career & Money", "all", False, True),
    ("What is burnout and how do you recover from it?", "Career & Money", "all", False, True),
    ("How do you balance ambition and relationships?", "Career & Money", "all", False, True),
    ("What are the signs you need a career change?", "Career & Money", "all", False, True),
    ("How do you set financial goals that actually stick?", "Career & Money", "all", False, True),
    ("What is a Roth IRA and should women have one?", "Career & Money", "all", False, True),
    ("How do you handle being laid off financially and emotionally?", "Career & Money", "all", False, True),
    ("What are the best books on money for women?", "Career & Money", "all", False, False),
    ("How do you build credit as a woman on your own?", "Career & Money", "20s,30s", False, True),
    ("What financial documents should every woman have in order?", "Career & Money", "all", False, True),
    ("How do you stop being afraid to look at your finances?", "Career & Money", "all", False, True),
    ("What are the best ways for women to network professionally?", "Career & Money", "all", False, True),
    ("How do you manage work-life balance without burning out?", "Career & Money", "all", False, True),
    ("What do women wish they knew about money in their 20s?", "Career & Money", "20s", False, True),
    # ── MENTAL HEALTH (40) ───────────────────────────────────────────
    ("What are the signs of anxiety vs normal stress?", "Mental Health", "all", False, True),
    ("What is the best therapy for anxiety in women?", "Mental Health", "all", False, True),
    ("How do you know if you have depression or just burnout?", "Mental Health", "all", False, True),
    ("What causes anxiety to suddenly get worse?", "Mental Health", "all", False, True),
    ("How do you manage anxiety without medication?", "Mental Health", "all", False, True),
    ("What is the difference between therapy types like CBT and DBT?", "Mental Health", "all", False, True),
    ("Why do women experience more anxiety and depression than men?", "Mental Health", "all", False, True),
    ("What are signs of high-functioning depression?", "Mental Health", "all", False, True),
    ("How do hormones affect mental health in women?", "Mental Health", "all", False, True),
    ("What is the best way to find a therapist?", "Mental Health", "all", False, True),
    ("What causes panic attacks and how do you stop them?", "Mental Health", "all", False, True),
    ("How do you support someone with depression?", "Mental Health", "all", False, True),
    ("What is the connection between gut health and mental health?", "Mental Health", "all", False, True),
    ("What are signs you need to take a mental health break?", "Mental Health", "all", False, True),
    ("How do you stop catastrophizing and overthinking?", "Mental Health", "all", False, True),
    ("Is ADHD underdiagnosed in women?", "Mental Health", "all", False, True),
    ("What are the symptoms of ADHD in adult women?", "Mental Health", "all", False, True),
    ("How do you build emotional resilience?", "Mental Health", "all", False, True),
    ("What are the signs of postpartum depression?", "Mental Health", "30s", False, True),
    ("How do you set boundaries without guilt?", "Mental Health", "all", False, True),
    ("What causes people-pleasing behavior and how to change it?", "Mental Health", "all", False, True),
    ("How do you deal with grief that doesnt go away?", "Mental Health", "all", False, True),
    ("What is the difference between sadness and clinical depression?", "Mental Health", "all", False, True),
    ("How does sleep deprivation affect mental health in women?", "Mental Health", "all", False, True),
    ("What are practical daily habits for better mental health?", "Mental Health", "all", False, True),
    ("How do you manage seasonal depression?", "Mental Health", "all", False, True),
    ("What is somatic therapy and does it work?", "Mental Health", "all", False, False),
    ("How do you stop feeling overwhelmed all the time?", "Mental Health", "all", False, True),
    ("What causes low self-esteem in adult women?", "Mental Health", "all", False, True),
    ("How do you talk to a doctor about mental health?", "Mental Health", "all", False, True),
    ("What are the side effects of antidepressants for women?", "Mental Health", "all", False, True),
    ("How do you recover from a traumatic relationship?", "Mental Health", "all", False, True),
    ("What is complex PTSD and how is it different from PTSD?", "Mental Health", "all", False, True),
    ("How do you stop seeking external validation?", "Mental Health", "all", False, True),
    ("What are the signs of burnout vs depression?", "Mental Health", "all", False, True),
    ("Is online therapy as effective as in-person therapy?", "Mental Health", "all", False, True),
    ("How do you practice mindfulness when you cant sit still?", "Mental Health", "all", False, False),
    ("What does healing from childhood trauma look like for women?", "Mental Health", "all", False, True),
    ("How do you manage mental health while going through menopause?", "Mental Health", "40s,50s+", False, True),
    ("What is the best way to reduce stress for busy women?", "Mental Health", "all", False, True),
    # ── PARENTING (30) ───────────────────────────────────────────────
    ("How do you manage mom guilt?", "Parenting", "30s,40s", False, True),
    ("What are signs of postpartum anxiety?", "Parenting", "30s", False, True),
    ("Is it normal to feel like you lost yourself after having kids?", "Parenting", "30s,40s", False, True),
    ("How do you maintain your relationship with your partner after kids?", "Parenting", "30s,40s", False, True),
    ("What are realistic expectations for returning to work after maternity leave?", "Parenting", "30s", False, True),
    ("How do you raise confident daughters?", "Parenting", "30s,40s", False, True),
    ("What is the best way to talk to kids about their bodies and puberty?", "Parenting", "30s,40s", False, True),
    ("How do you stop yelling at your kids when youre overwhelmed?", "Parenting", "30s,40s", False, True),
    ("What is gentle parenting and does it work?", "Parenting", "30s,40s", False, True),
    ("How do single mothers manage everything without burning out?", "Parenting", "30s,40s", False, True),
    ("What do you do when your child wont listen?", "Parenting", "30s,40s", False, False),
    ("How do you balance self-care and being a good mom?", "Parenting", "30s,40s", False, True),
    ("What are signs of postpartum depression in new moms?", "Parenting", "30s", False, True),
    ("How do you co-parent effectively after a breakup?", "Parenting", "30s,40s", False, True),
    ("What are the best ways to get kids to sleep through the night?", "Parenting", "30s,40s", False, True),
    ("How do you handle screen time with toddlers and young kids?", "Parenting", "30s,40s", False, True),
    ("Is it okay to let kids fail sometimes?", "Parenting", "30s,40s", False, False),
    ("What are the best ways to bond with your baby?", "Parenting", "30s", False, True),
    ("How do you know if your child needs therapy?", "Parenting", "30s,40s", False, True),
    ("What are signs of anxiety in kids?", "Parenting", "30s,40s", False, True),
    ("How do you handle a difficult mother-in-law?", "Parenting", "30s,40s", False, True),
    ("What is the hardest thing about being a mom no one talks about?", "Parenting", "30s,40s", False, True),
    ("How do you rebuild your identity after becoming a mom?", "Parenting", "30s,40s", False, True),
    ("Is it normal to not enjoy every stage of parenting?", "Parenting", "30s,40s", False, True),
    ("How do you raise kids with healthy attitudes about food?", "Parenting", "30s,40s", False, True),
    ("What are the signs of childhood ADHD in girls?", "Parenting", "30s,40s", False, True),
    ("How do you handle the emotional weight of parenting alone?", "Parenting", "30s,40s", False, True),
    ("What is the best way to handle toddler tantrums?", "Parenting", "30s", False, False),
    ("How do you teach kids about consent and boundaries?", "Parenting", "30s,40s", False, True),
    ("Is it okay to breastfeed past one year?", "Parenting", "30s", False, False),
    # ── SKIN, HAIR & BEAUTY (30) ─────────────────────────────────────
    ("What is the best skincare routine for hormonal acne?", "Skin, Hair & Beauty", "all", False, True),
    ("What causes hair thinning in women and what actually helps?", "Skin, Hair & Beauty", "all", False, True),
    ("What is the correct order to apply skincare products?", "Skin, Hair & Beauty", "all", False, True),
    ("Does collagen supplementation actually work for skin?", "Skin, Hair & Beauty", "all", False, True),
    ("What are the best ingredients for anti-aging skincare?", "Skin, Hair & Beauty", "all", False, True),
    ("What causes dark circles under the eyes and how to fix them?", "Skin, Hair & Beauty", "all", False, True),
    ("What is the best sunscreen for everyday use?", "Skin, Hair & Beauty", "all", False, True),
    ("Is retinol safe to use and how do you start?", "Skin, Hair & Beauty", "all", False, True),
    ("What causes hormonal hair loss in women?", "Skin, Hair & Beauty", "all", False, True),
    ("What are the signs of skin purging vs breakouts?", "Skin, Hair & Beauty", "all", False, True),
    ("What is the best skincare routine for women over 40?", "Skin, Hair & Beauty", "40s,50s+", False, True),
    ("Does stress cause hair loss in women?", "Skin, Hair & Beauty", "all", False, True),
    ("What is the best moisturizer for dry and sensitive skin?", "Skin, Hair & Beauty", "all", False, False),
    ("What causes hyperpigmentation and how to treat it?", "Skin, Hair & Beauty", "all", False, True),
    ("Is vitamin C serum worth using?", "Skin, Hair & Beauty", "all", False, True),
    ("What foods are best for clear glowing skin?", "Skin, Hair & Beauty", "all", False, True),
    ("What is the best treatment for dark spots?", "Skin, Hair & Beauty", "all", False, True),
    ("How do you get rid of body acne?", "Skin, Hair & Beauty", "all", False, True),
    ("What are the best products for curly hair?", "Skin, Hair & Beauty", "all", False, False),
    ("Is niacinamide good for every skin type?", "Skin, Hair & Beauty", "all", False, False),
    ("What causes perioral dermatitis and how to treat it?", "Skin, Hair & Beauty", "all", False, True),
    ("How do you repair a damaged skin barrier?", "Skin, Hair & Beauty", "all", False, True),
    ("What is the difference between chemical and physical sunscreen?", "Skin, Hair & Beauty", "all", False, False),
    ("What causes brittle nails in women?", "Skin, Hair & Beauty", "all", False, False),
    ("How do you build a skincare routine from scratch?", "Skin, Hair & Beauty", "all", False, True),
    ("What are the best treatments for fine lines in your 30s?", "Skin, Hair & Beauty", "30s", False, True),
    ("Does drinking more water actually improve your skin?", "Skin, Hair & Beauty", "all", False, False),
    ("What is slugging and does it help dry skin?", "Skin, Hair & Beauty", "all", False, False),
    ("What causes scalp issues like dandruff or oiliness in women?", "Skin, Hair & Beauty", "all", False, False),
    ("How does hormonal birth control affect skin?", "Skin, Hair & Beauty", "all", False, True),
    # ── PREGNANCY & FERTILITY (40) ───────────────────────────────────
    ("What are the early signs of pregnancy before a missed period?", "Pregnancy & Fertility", "20s,30s", False, True),
    ("How long does it take to get pregnant after stopping birth control?", "Pregnancy & Fertility", "20s,30s", False, True),
    ("What is the best age to get pregnant?", "Pregnancy & Fertility", "20s,30s", False, True),
    ("What are signs of low fertility in women?", "Pregnancy & Fertility", "20s,30s", False, True),
    ("What are the most common causes of infertility in women?", "Pregnancy & Fertility", "20s,30s", False, True),
    ("What vitamins should I take when trying to get pregnant?", "Pregnancy & Fertility", "20s,30s", False, True),
    ("What is AMH and what does it tell you about your fertility?", "Pregnancy & Fertility", "20s,30s", False, True),
    ("Can PCOS affect fertility?", "Pregnancy & Fertility", "20s,30s", False, True),
    ("What should I know about egg freezing?", "Pregnancy & Fertility", "20s,30s", False, True),
    ("How does age affect fertility in women?", "Pregnancy & Fertility", "20s,30s", False, True),
    ("What is IVF and who is it recommended for?", "Pregnancy & Fertility", "20s,30s", False, True),
    ("What are signs of a healthy pregnancy in the first trimester?", "Pregnancy & Fertility", "20s,30s", False, True),
    ("What foods should you avoid when pregnant?", "Pregnancy & Fertility", "20s,30s", False, True),
    ("Is it safe to exercise during pregnancy?", "Pregnancy & Fertility", "20s,30s", False, True),
    ("What causes morning sickness and what actually helps?", "Pregnancy & Fertility", "20s,30s", False, True),
    ("How do you know if youre having a miscarriage?", "Pregnancy & Fertility", "20s,30s", False, True),
    ("What are the most common pregnancy complications?", "Pregnancy & Fertility", "20s,30s", False, True),
    ("How do you prepare your body for pregnancy?", "Pregnancy & Fertility", "20s,30s", False, True),
    ("What happens to your hormones during pregnancy?", "Pregnancy & Fertility", "20s,30s", False, True),
    ("What is gestational diabetes and who is at risk?", "Pregnancy & Fertility", "20s,30s", False, True),
    ("What does implantation bleeding look like?", "Pregnancy & Fertility", "20s,30s", False, True),
    ("How do you manage anxiety during pregnancy?", "Pregnancy & Fertility", "20s,30s", False, True),
    ("What are signs of a chemical pregnancy?", "Pregnancy & Fertility", "20s,30s", False, False),
    ("What is a natural birth vs medicated birth and whats better?", "Pregnancy & Fertility", "20s,30s", False, True),
    ("What are the risks of having a baby after 35?", "Pregnancy & Fertility", "30s", False, True),
    ("What should you know about postpartum recovery?", "Pregnancy & Fertility", "20s,30s", False, True),
    ("How does breastfeeding affect your hormones and body?", "Pregnancy & Fertility", "20s,30s", False, True),
    ("What is a VBAC and is it safe?", "Pregnancy & Fertility", "20s,30s", False, False),
    ("What are realistic expectations for fertility treatment?", "Pregnancy & Fertility", "20s,30s", False, True),
    ("What causes recurrent miscarriages?", "Pregnancy & Fertility", "20s,30s", False, True),
    ("How does stress affect fertility in women?", "Pregnancy & Fertility", "20s,30s", False, True),
    ("What is the two-week wait and how do you cope with it?", "Pregnancy & Fertility", "20s,30s", False, False),
    ("What does a positive ovulation test mean?", "Pregnancy & Fertility", "20s,30s", False, False),
    ("How do you track ovulation accurately?", "Pregnancy & Fertility", "20s,30s", False, True),
    ("What is the best time of month to try to conceive?", "Pregnancy & Fertility", "20s,30s", False, True),
    ("What are signs of an ectopic pregnancy?", "Pregnancy & Fertility", "20s,30s", False, True),
    ("How does endometriosis affect pregnancy chances?", "Pregnancy & Fertility", "20s,30s", False, True),
    ("What is the difference between primary and secondary infertility?", "Pregnancy & Fertility", "20s,30s", False, False),
    ("What are the emotional stages of dealing with infertility?", "Pregnancy & Fertility", "20s,30s", False, True),
    ("Can lifestyle changes actually improve fertility?", "Pregnancy & Fertility", "20s,30s", False, True),
    # ── WEIRD/VIRAL (50) ─────────────────────────────────────────────
    ("Why do I cry at commercials but not at real problems?", "Weird/Viral", "all", True, True),
    ("Is it normal to smell your own hair all day?", "Weird/Viral", "all", True, True),
    ("Why do I get irrationally angry when Im hungry?", "Weird/Viral", "all", True, True),
    ("What happens to your brain when you stalk your ex online?", "Weird/Viral", "all", True, True),
    ("Why do I feel more attractive right before my period?", "Weird/Viral", "all", True, True),
    ("Is it weird that I talk to myself out loud when Im alone?", "Weird/Viral", "all", True, True),
    ("Why do I get obsessed with a new interest for 3 weeks and then drop it?", "Weird/Viral", "all", True, True),
    ("What causes that feeling of falling right as you fall asleep?", "Weird/Viral", "all", True, True),
    ("Why do I always feel guilty even when I did nothing wrong?", "Weird/Viral", "all", True, True),
    ("Is it normal to feel better after a good cry?", "Weird/Viral", "all", True, True),
    ("Why do I find sad music comforting when Im sad?", "Weird/Viral", "all", True, True),
    ("What happens to your body when you blush?", "Weird/Viral", "all", True, True),
    ("Why do I remember embarrassing moments from 15 years ago at 2am?", "Weird/Viral", "all", True, True),
    ("Is it normal to have a specific side of the bed you always sleep on?", "Weird/Viral", "all", True, False),
    ("Why do I suddenly lose the word for something I say every day?", "Weird/Viral", "all", True, True),
    ("What causes that deep satisfaction of peeling something off?", "Weird/Viral", "all", True, True),
    ("Why does your voice sound different in recordings than in your head?", "Weird/Viral", "all", True, True),
    ("Is it normal to feel physical pain from emotional stress?", "Weird/Viral", "all", True, True),
    ("Why do I want to squeeze cute things so hard?", "Weird/Viral", "all", True, True),
    ("What is that random urge to jump from high places even though youre not suicidal?", "Weird/Viral", "all", True, True),
    ("Why does time feel like its moving faster as I get older?", "Weird/Viral", "all", True, True),
    ("What happens to your body when someone says your name in a crowd?", "Weird/Viral", "all", True, True),
    ("Why do I feel like Im forgetting to do something even when Im not?", "Weird/Viral", "all", True, True),
    ("What causes that weird awareness of your own breathing at night?", "Weird/Viral", "all", True, True),
    ("Why do some people hate the sound of other people chewing?", "Weird/Viral", "all", True, True),
    ("Is it normal to feel a strong emotional bond with a fictional character?", "Weird/Viral", "all", True, True),
    ("What causes the urge to confess something even when you dont have to?", "Weird/Viral", "all", True, True),
    ("Why do some people love the smell of old books?", "Weird/Viral", "all", True, False),
    ("What is the science behind getting chills from music?", "Weird/Viral", "all", True, True),
    ("Why do I suddenly have no idea how to walk normally when someone watches me?", "Weird/Viral", "all", True, True),
    ("What is that feeling of nostalgia for a time you never actually lived through?", "Weird/Viral", "all", True, True),
    ("Why does rejection feel physically painful?", "Weird/Viral", "all", True, True),
    ("Is it weird to feel lonely even when youre surrounded by people?", "Weird/Viral", "all", True, True),
    ("What causes the sudden urge to text your ex at night?", "Weird/Viral", "all", True, True),
    ("Why do I feel worse about myself after scrolling social media?", "Weird/Viral", "all", True, True),
    ("What is the science behind falling in love with someones voice?", "Weird/Viral", "all", True, True),
    ("Why do I always feel like Im the only one who doesnt have it together?", "Weird/Viral", "all", True, True),
    ("What happens in your brain when you get a compliment you dont believe?", "Weird/Viral", "all", True, True),
    ("Why do I always remember the worst version of something I said?", "Weird/Viral", "all", True, True),
    ("Is it normal to have a strong preference for a specific type of pen?", "Weird/Viral", "all", True, False),
    ("What causes the urge to eat ice?", "Weird/Viral", "all", True, True),
    ("Why do I feel like Im being watched when Im alone at night?", "Weird/Viral", "all", True, False),
    ("What causes that midnight hunger even after a full dinner?", "Weird/Viral", "all", True, True),
    ("Why do some people tear up at national anthems?", "Weird/Viral", "all", True, False),
    ("What causes that satisfying feeling when you crack your knuckles?", "Weird/Viral", "all", True, False),
    ("Is it normal to feel deeply sad about something that never happened to you?", "Weird/Viral", "all", True, True),
    ("Why do women often apologize for things that arent their fault?", "Weird/Viral", "all", True, True),
    ("What happens to your brain when you ghosted someone and feel guilty about it?", "Weird/Viral", "all", True, True),
    ("Why do I feel productive anxiety the night before a big day?", "Weird/Viral", "all", True, True),
    ("Is it normal to feel relief when plans get cancelled?", "Weird/Viral", "all", True, True),
]

# ── SQL GENERATION ────────────────────────────────────────────────────────
seen_slugs = {}
insert_rows = []

for q, cat, age, weird, featured in questions:
    slug = slugify(q)
    if slug in seen_slugs:
        slug = slug + "-alt"
    seen_slugs[slug] = True
    q_esc = q.replace("'", "''")
    cat_esc = cat.replace("'", "''")
    meta_title = f"{q} | 4 AIs Weigh In".replace("'", "''")
    meta_desc = f"We asked ChatGPT, Gemini, Claude, and Grok: {q} See where they agreed and where they disagreed.".replace("'", "''")
    insert_rows.append(
        f"  ('{slug}', '{q_esc}', '{cat_esc}', '{age}', {str(weird).lower()}, {str(featured).lower()}, '{meta_title}', '{meta_desc}')"
    )

sql_parts = []
sql_parts.append("-- 007_curated_questions.sql")
sql_parts.append("-- Curated questions library for AskWomensAI\n")
sql_parts.append("""CREATE TABLE IF NOT EXISTS public.curated_questions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slug text UNIQUE NOT NULL,
  question text NOT NULL,
  category text NOT NULL,
  age_group text,
  is_weird boolean DEFAULT false,
  is_featured boolean DEFAULT false,
  search_request_id uuid REFERENCES search_requests(id),
  meta_title text,
  meta_description text,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_curated_questions_category ON public.curated_questions(category);
CREATE INDEX IF NOT EXISTS idx_curated_questions_age_group ON public.curated_questions(age_group);
CREATE INDEX IF NOT EXISTS idx_curated_questions_is_weird ON public.curated_questions(is_weird);
CREATE INDEX IF NOT EXISTS idx_curated_questions_is_featured ON public.curated_questions(is_featured);
""")
sql_parts.append("INSERT INTO public.curated_questions (slug, question, category, age_group, is_weird, is_featured, meta_title, meta_description)")
sql_parts.append("VALUES")
sql_parts.append(",\n".join(insert_rows))
sql_parts.append("ON CONFLICT (slug) DO NOTHING;\n")
sql_parts.append(f"-- Total: {len(insert_rows)} questions")

sql = "\n".join(sql_parts)
out = r"C:\Users\rbend\Desktop\womensai\supabase\migrations\007_curated_questions.sql"
with open(out, "w", encoding="utf-8") as f:
    f.write(sql)

from collections import Counter
cats = Counter(q[1] for q in questions)
print(f"Written {len(insert_rows)} questions to 007_curated_questions.sql")
for cat, cnt in sorted(cats.items()):
    print(f"  {cat}: {cnt}")
print(f"  TOTAL: {sum(cats.values())}")
